services:
  - type: web
    name: ecowastsolutions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn other.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: rzp_test_h2s4PxBwrmOiSL
      - key: RAZORPAY_KEY_SECRET
        value: beJB0s8KqtrFC8JnRjpJsYOl
      - key: DATABASE_URL
        fromDatabase:
          name: ecowastsolutions-db
          property: connectionString

databases:
  - name: ecowastsolutions-db
    databaseName: metal_waste_db
    user: metal_waste_user
    plan: free 