services:
  - type: web
    name: ecowastsolutions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn other.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ecowastsolutions-db
          property: connectionString

databases:
  - name: ecowastsolutions-db
    databaseName: metal_waste_db
    user: metal_waste_user
    plan: free
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1 